version: "3"
services:
  casadbserver:
    image: "postgres:13.1"
    container_name: "local-postgres-order-management"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_management
      LC_COLLATE: en_US.utf8
      LC_CTYPE: en_US.utf8
      ENCODING: UTF8
      TEMPLATE: template0
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "54339:5432"

#  localstack:
#    container_name: "${LOCALSTACK_DOCKER-localstack}"
#    image: localstack/localstack:0.11.2
#    hostname: localstack
#    ports:
#      - "4566-4599:4566-4599"
#      - "${PORT_WEB_UI-1111}:${PORT_WEB_UI-1111}"
#    environment:
#      - SERVICES=s3,sqs
#      - DEBUG=1
#      - PORT_WEB_UI=1111
#      - LAMBDA_EXECUTOR=docker-reuse
#      - LAMBDA_REMOTE_DOCKER=false
#      - LAMBDA_REMOVE_CONTAINERS=true
#      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
#      - DOCKER_HOST=unix:///var/run/docker.sock
#      - HOST_TMP_FOLDER=${TMPDIR}
#    volumes:
#      - "/tmp/localstack:/tmp/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - ./bin:/docker-entrypoint-initaws.d

#  sonarqube:
#    image: sonarqube
#    expose:
#      - 9000
#    ports:
#      - "127.0.0.1:9000:9000"
#    volumes:
#      - sonarqube_data:/opt/sonarqube/data